//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("masterModel", "FK__Studentin__cours__66B53B20", "courseinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.courseinfo), "Studentinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Studentinfo), true)]
[assembly: EdmRelationshipAttribute("masterModel", "FK__emp__DEPTNO__5E1FF51F", "dept", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.dept), "emp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.emp), true)]

#endregion

namespace DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class masterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new masterEntities object using the connection string found in the 'masterEntities' section of the application configuration file.
        /// </summary>
        public masterEntities() : base("name=masterEntities", "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new masterEntities object.
        /// </summary>
        public masterEntities(string connectionString) : base(connectionString, "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new masterEntities object.
        /// </summary>
        public masterEntities(EntityConnection connection) : base(connection, "masterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Logininfo> Logininfoes
        {
            get
            {
                if ((_Logininfoes == null))
                {
                    _Logininfoes = base.CreateObjectSet<Logininfo>("Logininfoes");
                }
                return _Logininfoes;
            }
        }
        private ObjectSet<Logininfo> _Logininfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<courseinfo> courseinfoes
        {
            get
            {
                if ((_courseinfoes == null))
                {
                    _courseinfoes = base.CreateObjectSet<courseinfo>("courseinfoes");
                }
                return _courseinfoes;
            }
        }
        private ObjectSet<courseinfo> _courseinfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Registration> Registrations
        {
            get
            {
                if ((_Registrations == null))
                {
                    _Registrations = base.CreateObjectSet<Registration>("Registrations");
                }
                return _Registrations;
            }
        }
        private ObjectSet<Registration> _Registrations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Studentinfo> Studentinfoes
        {
            get
            {
                if ((_Studentinfoes == null))
                {
                    _Studentinfoes = base.CreateObjectSet<Studentinfo>("Studentinfoes");
                }
                return _Studentinfoes;
            }
        }
        private ObjectSet<Studentinfo> _Studentinfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dept> depts
        {
            get
            {
                if ((_depts == null))
                {
                    _depts = base.CreateObjectSet<dept>("depts");
                }
                return _depts;
            }
        }
        private ObjectSet<dept> _depts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<emp> emps
        {
            get
            {
                if ((_emps == null))
                {
                    _emps = base.CreateObjectSet<emp>("emps");
                }
                return _emps;
            }
        }
        private ObjectSet<emp> _emps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logininfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogininfoes(Logininfo logininfo)
        {
            base.AddObject("Logininfoes", logininfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the courseinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocourseinfoes(courseinfo courseinfo)
        {
            base.AddObject("courseinfoes", courseinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Registrations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistrations(Registration registration)
        {
            base.AddObject("Registrations", registration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Studentinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentinfoes(Studentinfo studentinfo)
        {
            base.AddObject("Studentinfoes", studentinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the depts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepts(dept dept)
        {
            base.AddObject("depts", dept);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemps(emp emp)
        {
            base.AddObject("emps", emp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="courseinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class courseinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new courseinfo object.
        /// </summary>
        /// <param name="cid">Initial value of the cid property.</param>
        /// <param name="coursename">Initial value of the coursename property.</param>
        public static courseinfo Createcourseinfo(global::System.Int32 cid, global::System.String coursename)
        {
            courseinfo courseinfo = new courseinfo();
            courseinfo.cid = cid;
            courseinfo.coursename = coursename;
            return courseinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                if (_cid != value)
                {
                    OncidChanging(value);
                    ReportPropertyChanging("cid");
                    _cid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cid");
                    OncidChanged();
                }
            }
        }
        private global::System.Int32 _cid;
        partial void OncidChanging(global::System.Int32 value);
        partial void OncidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String coursename
        {
            get
            {
                return _coursename;
            }
            set
            {
                OncoursenameChanging(value);
                ReportPropertyChanging("coursename");
                _coursename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("coursename");
                OncoursenameChanged();
            }
        }
        private global::System.String _coursename;
        partial void OncoursenameChanging(global::System.String value);
        partial void OncoursenameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("masterModel", "FK__Studentin__cours__66B53B20", "Studentinfo")]
        public EntityCollection<Studentinfo> Studentinfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Studentinfo>("masterModel.FK__Studentin__cours__66B53B20", "Studentinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Studentinfo>("masterModel.FK__Studentin__cours__66B53B20", "Studentinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="dept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dept : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dept object.
        /// </summary>
        /// <param name="deptno">Initial value of the deptno property.</param>
        public static dept Createdept(global::System.Int32 deptno)
        {
            dept dept = new dept();
            dept.deptno = deptno;
            return dept;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 deptno
        {
            get
            {
                return _deptno;
            }
            set
            {
                if (_deptno != value)
                {
                    OndeptnoChanging(value);
                    ReportPropertyChanging("deptno");
                    _deptno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("deptno");
                    OndeptnoChanged();
                }
            }
        }
        private global::System.Int32 _deptno;
        partial void OndeptnoChanging(global::System.Int32 value);
        partial void OndeptnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dname
        {
            get
            {
                return _dname;
            }
            set
            {
                OndnameChanging(value);
                ReportPropertyChanging("dname");
                _dname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dname");
                OndnameChanged();
            }
        }
        private global::System.String _dname;
        partial void OndnameChanging(global::System.String value);
        partial void OndnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loc
        {
            get
            {
                return _loc;
            }
            set
            {
                OnlocChanging(value);
                ReportPropertyChanging("loc");
                _loc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loc");
                OnlocChanged();
            }
        }
        private global::System.String _loc;
        partial void OnlocChanging(global::System.String value);
        partial void OnlocChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("masterModel", "FK__emp__DEPTNO__5E1FF51F", "emp")]
        public EntityCollection<emp> emps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<emp>("masterModel.FK__emp__DEPTNO__5E1FF51F", "emp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<emp>("masterModel.FK__emp__DEPTNO__5E1FF51F", "emp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="emp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class emp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new emp object.
        /// </summary>
        /// <param name="eMPNO">Initial value of the EMPNO property.</param>
        public static emp Createemp(global::System.Int32 eMPNO)
        {
            emp emp = new emp();
            emp.EMPNO = eMPNO;
            return emp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EMPNO
        {
            get
            {
                return _EMPNO;
            }
            set
            {
                if (_EMPNO != value)
                {
                    OnEMPNOChanging(value);
                    ReportPropertyChanging("EMPNO");
                    _EMPNO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EMPNO");
                    OnEMPNOChanged();
                }
            }
        }
        private global::System.Int32 _EMPNO;
        partial void OnEMPNOChanging(global::System.Int32 value);
        partial void OnEMPNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENAME
        {
            get
            {
                return _ENAME;
            }
            set
            {
                OnENAMEChanging(value);
                ReportPropertyChanging("ENAME");
                _ENAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENAME");
                OnENAMEChanged();
            }
        }
        private global::System.String _ENAME;
        partial void OnENAMEChanging(global::System.String value);
        partial void OnENAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JOB
        {
            get
            {
                return _JOB;
            }
            set
            {
                OnJOBChanging(value);
                ReportPropertyChanging("JOB");
                _JOB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JOB");
                OnJOBChanged();
            }
        }
        private global::System.String _JOB;
        partial void OnJOBChanging(global::System.String value);
        partial void OnJOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MGR
        {
            get
            {
                return _MGR;
            }
            set
            {
                OnMGRChanging(value);
                ReportPropertyChanging("MGR");
                _MGR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MGR");
                OnMGRChanged();
            }
        }
        private Nullable<global::System.Int32> _MGR;
        partial void OnMGRChanging(Nullable<global::System.Int32> value);
        partial void OnMGRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HIREDATE
        {
            get
            {
                return _HIREDATE;
            }
            set
            {
                OnHIREDATEChanging(value);
                ReportPropertyChanging("HIREDATE");
                _HIREDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HIREDATE");
                OnHIREDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _HIREDATE;
        partial void OnHIREDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnHIREDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SAL
        {
            get
            {
                return _SAL;
            }
            set
            {
                OnSALChanging(value);
                ReportPropertyChanging("SAL");
                _SAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SAL");
                OnSALChanged();
            }
        }
        private Nullable<global::System.Decimal> _SAL;
        partial void OnSALChanging(Nullable<global::System.Decimal> value);
        partial void OnSALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> COMM
        {
            get
            {
                return _COMM;
            }
            set
            {
                OnCOMMChanging(value);
                ReportPropertyChanging("COMM");
                _COMM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COMM");
                OnCOMMChanged();
            }
        }
        private Nullable<global::System.Decimal> _COMM;
        partial void OnCOMMChanging(Nullable<global::System.Decimal> value);
        partial void OnCOMMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DEPTNO
        {
            get
            {
                return _DEPTNO;
            }
            set
            {
                OnDEPTNOChanging(value);
                ReportPropertyChanging("DEPTNO");
                _DEPTNO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEPTNO");
                OnDEPTNOChanged();
            }
        }
        private Nullable<global::System.Int32> _DEPTNO;
        partial void OnDEPTNOChanging(Nullable<global::System.Int32> value);
        partial void OnDEPTNOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("masterModel", "FK__emp__DEPTNO__5E1FF51F", "dept")]
        public dept dept
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dept>("masterModel.FK__emp__DEPTNO__5E1FF51F", "dept").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dept>("masterModel.FK__emp__DEPTNO__5E1FF51F", "dept").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dept> deptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dept>("masterModel.FK__emp__DEPTNO__5E1FF51F", "dept");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dept>("masterModel.FK__emp__DEPTNO__5E1FF51F", "dept", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="Logininfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Logininfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Logininfo object.
        /// </summary>
        /// <param name="mobno">Initial value of the mobno property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static Logininfo CreateLogininfo(global::System.Int64 mobno, global::System.String password)
        {
            Logininfo logininfo = new Logininfo();
            logininfo.mobno = mobno;
            logininfo.password = password;
            return logininfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 mobno
        {
            get
            {
                return _mobno;
            }
            set
            {
                if (_mobno != value)
                {
                    OnmobnoChanging(value);
                    ReportPropertyChanging("mobno");
                    _mobno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mobno");
                    OnmobnoChanged();
                }
            }
        }
        private global::System.Int64 _mobno;
        partial void OnmobnoChanging(global::System.Int64 value);
        partial void OnmobnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="Registration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Registration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Registration object.
        /// </summary>
        /// <param name="regID">Initial value of the RegID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Registration CreateRegistration(global::System.Int32 regID, global::System.String name, global::System.String address)
        {
            Registration registration = new Registration();
            registration.RegID = regID;
            registration.Name = name;
            registration.Address = address;
            return registration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RegID
        {
            get
            {
                return _RegID;
            }
            set
            {
                if (_RegID != value)
                {
                    OnRegIDChanging(value);
                    ReportPropertyChanging("RegID");
                    _RegID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegID");
                    OnRegIDChanged();
                }
            }
        }
        private global::System.Int32 _RegID;
        partial void OnRegIDChanging(global::System.Int32 value);
        partial void OnRegIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Qualification
        {
            get
            {
                return _Qualification;
            }
            set
            {
                OnQualificationChanging(value);
                ReportPropertyChanging("Qualification");
                _Qualification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Qualification");
                OnQualificationChanged();
            }
        }
        private global::System.String _Qualification;
        partial void OnQualificationChanging(global::System.String value);
        partial void OnQualificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SkillSets
        {
            get
            {
                return _SkillSets;
            }
            set
            {
                OnSkillSetsChanging(value);
                ReportPropertyChanging("SkillSets");
                _SkillSets = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SkillSets");
                OnSkillSetsChanged();
            }
        }
        private global::System.String _SkillSets;
        partial void OnSkillSetsChanging(global::System.String value);
        partial void OnSkillSetsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hobbies
        {
            get
            {
                return _Hobbies;
            }
            set
            {
                OnHobbiesChanging(value);
                ReportPropertyChanging("Hobbies");
                _Hobbies = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hobbies");
                OnHobbiesChanged();
            }
        }
        private global::System.String _Hobbies;
        partial void OnHobbiesChanging(global::System.String value);
        partial void OnHobbiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOJ
        {
            get
            {
                return _DOJ;
            }
            set
            {
                OnDOJChanging(value);
                ReportPropertyChanging("DOJ");
                _DOJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOJ");
                OnDOJChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOJ;
        partial void OnDOJChanging(Nullable<global::System.DateTime> value);
        partial void OnDOJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private Nullable<global::System.Decimal> _Salary;
        partial void OnSalaryChanging(Nullable<global::System.Decimal> value);
        partial void OnSalaryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="masterModel", Name="Studentinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Studentinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Studentinfo object.
        /// </summary>
        /// <param name="rollno">Initial value of the rollno property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Studentinfo CreateStudentinfo(global::System.Int32 rollno, global::System.String name)
        {
            Studentinfo studentinfo = new Studentinfo();
            studentinfo.rollno = rollno;
            studentinfo.name = name;
            return studentinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rollno
        {
            get
            {
                return _rollno;
            }
            set
            {
                if (_rollno != value)
                {
                    OnrollnoChanging(value);
                    ReportPropertyChanging("rollno");
                    _rollno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rollno");
                    OnrollnoChanged();
                }
            }
        }
        private global::System.Int32 _rollno;
        partial void OnrollnoChanging(global::System.Int32 value);
        partial void OnrollnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> courseid
        {
            get
            {
                return _courseid;
            }
            set
            {
                OncourseidChanging(value);
                ReportPropertyChanging("courseid");
                _courseid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("courseid");
                OncourseidChanged();
            }
        }
        private Nullable<global::System.Int32> _courseid;
        partial void OncourseidChanging(Nullable<global::System.Int32> value);
        partial void OncourseidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("masterModel", "FK__Studentin__cours__66B53B20", "courseinfo")]
        public courseinfo courseinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<courseinfo>("masterModel.FK__Studentin__cours__66B53B20", "courseinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<courseinfo>("masterModel.FK__Studentin__cours__66B53B20", "courseinfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<courseinfo> courseinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<courseinfo>("masterModel.FK__Studentin__cours__66B53B20", "courseinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<courseinfo>("masterModel.FK__Studentin__cours__66B53B20", "courseinfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
